# Generated by Django 3.2.7 on 2021-09-17 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 9, 17, 12, 27, 33, 468526)),
            preserve_default=False,
        ),
    ]
