# Generated by Django 3.2.7 on 2021-09-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_planning'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='uom',
            field=models.CharField(default='DEFAULT VALUE', max_length=140),
        ),
    ]
