# Generated by Django 3.2.7 on 2021-09-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_planning_uom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='uom',
            field=models.CharField(default='DEFAULT VALUE', max_length=255),
        ),
    ]
